apiVersion: v2
name: retail-store
description: Umbrella chart for Retail Store application
type: application
version: 1.0.0

dependencies:
  - name: retail-store-cart
    version: 0.0.1
    repository: "file://charts/cart"

  - name: retail-store-catalog
    version: 0.0.1
    repository: "file://charts/catalog"
  
  - name: retail-store-checkout
    version: 0.0.1
    repository: "file://charts/checkout"
  
  - name: retail-store-orders
    version: 0.0.1
    repository: "file://charts/orders"
  
  - name: retail-store-ui
    version: 0.0.1
    repository: "file://charts/ui"
  
  - name: retail-store-dynamodb
    version: 0.0.1
    repository: "file://charts/dynamodb"
  
  - name: retail-store-mysql
    version: 0.0.1
    repository: "file://charts/mysql"
  
  - name: retail-store-postgresql
    version: 0.0.1
    repository: "file://charts/postgresql"
  
  - name: retail-store-rabbitmq
    version: 0.0.1
    repository: "file://charts/rabbitmq"
  
  - name: retail-store-redis
    version: 0.0.1
    repository: "file://charts/redis"

    #NOTE:
      # name: retail-store-cart: This must match the name field inside charts/cart/Chart.yaml
      # and the keys in your values-prod.yaml.


# "helm dependency update" actually does:
# It reads your umbrella Chart.yaml, finds all the dependencies, packages each subchart into a .tgz file, and drops them into charts/ at the umbrella root.

# Two things get created:
# 1. .tgz files inside charts/
# Each subchart gets packaged into a tarball. When helm install runs, it reads these tarballs — not your source charts/cart/ folder directly. The .tgz is what actually gets deployed.
# 2. Chart.lock
# Records the exact version of every dependency that was resolved, like a package-lock.json. Guarantees reproducible installs — if someone else runs helm dependency build later, they get identical tarballs.
# automatically done by argocd