apiVersion: v2
name: retail-store
description: Umbrella chart for Retail Store application
type: application
version: 1.0.0

dependencies:
  - name: retail-store-cart
    version: 0.0.1
    repository: "file://charts/cart"

  - name: retail-store-catalog
    version: 0.0.1
    repository: "file://charts/catalog"
  
  - name: retail-store-checkout
    version: 0.0.1
    repository: "file://charts/checkout"
  
  - name: retail-store-orders
    version: 0.0.1
    repository: "file://charts/orders"
  
  - name: retail-store-ui
    version: 0.0.1
    repository: "file://charts/ui"
  
  - name: retail-store-dynamodb
    version: 0.0.1
    repository: "file://charts/dynamodb"
  
  - name: retail-store-mysql
    version: 0.0.1
    repository: "file://charts/mysql"
  
  - name: retail-store-postgresql
    version: 0.0.1
    repository: "file://charts/postgresql"
  
  - name: retail-store-rabbitmq
    version: 0.0.1
    repository: "file://charts/rabbitmq"
  
  - name: retail-store-redis
    version: 0.0.1
    repository: "file://charts/redis"

    #NOTE:
      # name: retail-store-cart: This must match the name field inside charts/cart/Chart.yaml
      # and the keys in your values-prod.yaml.