apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment    
  labels:
    app: ui              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: ui            
      environment: dev
      componet: frontend
  template:
    metadata:
      labels:
        app: ui          
        environment: dev
        componet: frontend
    spec:
      containers:
      - name: ui
        image: sarthak6700/retail-store-ui 
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: orders-configmap      
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-store
spec:
  type: NodePort
  selector:
    app: ui          
    environment: dev
    componet: frontend
  ports:
  - name: ui-service-port
    protocol: TCP
    port: 8080 
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configmap
  namespace: retail-store
data:
  # Postgresql
  RETAIL_UI_THEME: orange
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog:8080
  RETAIL_UI_ENDPOINTS_CARTS: http://cart:8080
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders:8080
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout:8080
  RETAIL_UI_CHAT_ENABLED: "false"