apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment    
  labels:
    app: catalog              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: catalog            
      environment: dev
      componet: backend
  template:
    metadata:
      labels:
        app: catalog          
        environment: dev
        componet: backend
    spec:
      containers:
      - name: catalog
        image: sarthak6700/retail-store-catalog      
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: retail-store
spec:
  selector:
    app: catalog          
    environment: dev
    componet: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 