pipeline {
    agent { node { label 'AGENT-1' } }

    stages {
        
        stage('Build') {
            steps {
                echo 'Building..'
              sh '''
                ls -ltr
                pwd
                echo "Building Docker Image"
                cd ./src/cart
                docker build -t retail-store-cart:v2 .
              '''
            }
        }
    }
    post { 
        always { 
            echo 'I will always run whether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}