pipeline {
    agent any // to give agent label 

    stages {
        stage('installing docker') {
            steps {
                echo 'installing..'
              sh '''
                pwd
                apt update
                apt install docker.io -y
                usermod -aG docker jenkins
                systemctl restart jenkins
                docker ps
              '''
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
              sh '''
                ls -ltr
                pwd
                echo "Building Docker Image"
                docker build -t retail-store-cart:v2 .
              '''
            }
        }
    }
    post { 
        always { 
            echo 'I will always run whether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}