pipeline {
    agent { node { label 'AGENT-1' } }

    environment {
        IMAGE_NAME = "" 
    }

    stages {
        stage('Get version') {
            steps {
                script {
                    env.VERSION = sh(
                        script: "cd src/cart && mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tail -n 1",
                        returnStdout: true
                    ).trim()

                    echo "Maven version detected: ${env.VERSION}"

                    env.IMAGE_NAME = "sarthak6700/retail-store-cart:${env.VERSION}"
                    
                    echo "Image name set to: ${env.IMAGE_NAME}"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    echo "Building Docker Image: ${env.IMAGE_NAME}"
                    cd src/cart
                    docker build -t ${env.IMAGE_NAME} .
                    """
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Image') {
            steps {
                script {
                    sh """
                    docker push ${env.IMAGE_NAME}
                    """
                }
            }
        }

        // stage('Deploy to Kubernetes') {
        //     steps {
        //         script {
        //             sh """
        //             kubectl set image deployment/cart cart=${env.IMAGE_NAME}
        //             """
        //         }
        //     }
        // }

        // stage('Verify Rollout') {
        //     steps {
        //         sh '''
        //         kubectl rollout status deployment/cart
        //         '''                
        //     }
        // }

        // stage('Health Check') {
        //     steps {
        //         sh '''
        //         sleep 10
        //         curl -f http://YOUR_SERVICE_URL/actuator/health
        //         '''
        //     }
        // }
    }

    post {
        failure {
            echo "Deployment failed — rolling back..."
            sh '''
            kubectl rollout undo deployment/cart
            '''
        }

        success {
            echo "Deployment successful!"
        }

        always {
            echo "Pipeline finished"
        }
    }
}