apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    environment: dev
    tier: db
  namespace: retail-store
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      environment: dev
      tier: db
  template:
    metadata:
      labels:
        environment: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
          name: mysql-port
        env: # contains all important variables to setup mysql
        - name: MYSQL_DATABASE
          value: catalogdb
        - name: MYSQL_USER
          value: catalog_user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class"  no storage of this name is available so will stay pending
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: retail-store
spec:
  selector: 
    environment: dev 
    tier: db
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: retail-store
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
