apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: retail-store
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgresql
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: retail-store
spec:
  selector:
    matchLabels:
      app: postgresql # has to match .spec.template.metadata.labels
  serviceName: "postgresql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgresql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: postgres_user
        - name: POSTGRES_DB #for db name
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: www
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class" only give if this name of volume is present
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque 
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  