apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment    
  labels:
    app: cart              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: cart            
      environment: dev
      component: backend
  template:
    metadata:
      labels:
        app: cart          
        environment: dev
        component: backend
    spec:
      containers:
      - name: cart
        image: sarthak6700/retail-store-cart:v1
        ports:
        - containerPort: 8080   
        envFrom:
        - configMapRef:
            name: cart-configmap
        - secretRef:
            name: secrets-basic-auth # here we are giving all the secret information 
---
apiVersion: v1
kind: Service
metadata:
  name: cart # if i give anyother name like cart-service ui will call http://cart-service:8080 not http://cart:8080
  namespace: retail-store
spec:
  selector:
    app: cart          
    environment: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: dynamodb
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: Items
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: http://dynamodb:8000
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "true"
  AWS_REGION: ap-south-1
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-basic-auth
  namespace: retail-store
stringData:
  AWS_ACCESS_KEY_ID: anything
  AWS_SECRET_ACCESS_KEY: anything
