apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog  
  labels:
    app: catalog              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: catalog            
      environment: dev
      component: backend
  template:
    metadata:
      labels:
        app: catalog          
        environment: dev
        component: backend
    spec:
      containers:
      - name: catalog
        image: sarthak6700/retail-store-catalog:v1    
        ports:
        - containerPort: 8080 
        envFrom:
        - configMapRef:
            name: catalog-map
        - secretRef:
            name: catalog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-store
spec:
  selector:
    app: catalog          
    environment: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: retail-store
  name: catalog-map
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: mysql
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: mysql:3306
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: catalogdb
  RETAIL_CATALOG_PERSISTENCE_USER: catalog_user
  RETAIL_CATALOG_PERSISTENCE_CONNECT_TIMEOUT: "5"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: retail-store
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: cGFzc3dvcmQ=

