apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment    
  labels:
    app: checkout              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: checkout            
      environment: dev
      componet: backend
  template:
    metadata:
      labels:
        app: checkout          
        environment: dev
        componet: backend
    spec:
      containers:
      - name: checkout
        image: sarthak6700/retail-store-checkout   
        ports:
        - containerPort: 8080  
        envFrom:
        - configMapRef:
            name: checkout-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-store
spec:
  selector:
    app: checkout          
    environment: dev
    componet: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-configmap
  namespace: retail-store
data:
  # Postgresql
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: redis
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: redis://redis:6379
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: http://orders:8080
  RETAIL_CHECKOUT_SHIPPING_NAME_PREFIX: checkout_complete