apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment    
  labels:
    app: orders              
    environment: dev
  namespace: retail-store
spec:
  replicas: 1               
  selector:
    matchLabels:
      app: orders            
      environment: dev
      component: backend
  template:
    metadata:
      labels:
        app: orders          
        environment: dev
        component: backend
    spec:
      containers:
      - name: orders
        image: sarthak6700/retail-store-orders    
        ports:
        - containerPort: 8080   
        envFrom:
        - configMapRef:
            name: orders-configmap
        - secretRef:
            name: orders-secret
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: retail-store
spec:
  selector:
    app: orders          
    environment: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-configmap
  namespace: retail-store
data:
  # Postgresql
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: postgresql:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: postgres
  RETAIL_ORDERS_PERSISTENCE_USERNAME: postgres_user
  # Rabbitmq
  # RETAIL_ORDERS_MESSAGING_PROVIDER: 
  # RETAIL_ORDERS_MESSAGING_SQS_TOPIC:
  # RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES:
  # RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME:
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: retail-store
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: cGFzc3dvcmQ=
  # RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: