apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment    
  labels:
    app: orders              
    environment: dev
  namespace: retail-store
spec:
  replicas: 2               
  selector:
    matchLabels:
      app: orders            
      environment: dev
      componet: backend
  template:
    metadata:
      labels:
        app: orders          
        environment: dev
        componet: backend
    spec:
      containers:
      - name: orders
        image: sarthak6700/retail-store-orders       
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: retail-store
spec:
  selector:
    app: orders          
    environment: dev
    componet: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 