apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.secrets.userPassword }}


# stringData vs data — simple version:
# yaml# data — YOU must base64 encode it yourself
# data:
#   MYSQL_PASSWORD: cGFzc3dvcmQ=   # you ran: echo -n "password" | base64

# # stringData — Kubernetes base64 encodes it for you
# stringData:
#   MYSQL_PASSWORD: password        # you write plain text, K8s handles encoding
# Both end up identical inside Kubernetes. stringData is just a convenience — you don't have to manually run base64 yourself.