{{- if eq .Values.aws.authMethod "static" }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-static-creds
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.secretAccessKey }}
{{- end }}

# Secrets are used for sensitive data because they support better access control, separation of concerns, and integration with 
# external secret managers. ConfigMaps are meant for non-sensitive configuration, and storing secrets there would expose them 
# as plain text and weaken security practices.