{{- if eq .Values.aws.authMethod "irsa" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
{{- end }}

# Definition
# A ServiceAccount in Kubernetes is an identity used by pods to interact with Kubernetes API or external services.
# Example statement:
# A Kubernetes ServiceAccount provides an identity for pods so they can securely access resources like AWS services without storing
# credentials inside containers.

